### ISSUE TITLE
feature request: use instance other than default cube?

### ISSUE THREAD

**Issue by jsnelgro** [Andy-Roger/Cubify#3]
Basically, I have a custom cube prefab and would like to generate a voxel mesh using it instead of the default unity cube. I can start working on a PR for this if you don't have time, but I thought I'd create an issue here to increase visibility. Thanks for making this plugin!

**Comment by Andy-Roger** [comment]
I am currently working a feature that lets you choose between other primitive shapes like spheres and cylinders. I could also include an option for custom meshes, thanks for the idea!

**Comment by Andy-Roger** [comment]
Custom shape support was added.
